
/* Drop Tables */

DROP TABLE SCOTT.APPROVAL CASCADE CONSTRAINTS;
DROP TABLE SCOTT.S_PARTI CASCADE CONSTRAINTS;
DROP TABLE SCOTT.S_REPLY CASCADE CONSTRAINTS;
DROP TABLE SCOTT.S_ENROLL CASCADE CONSTRAINTS;
DROP TABLE SCOTT.T_PARTI CASCADE CONSTRAINTS;
DROP TABLE SCOTT.T_REPLY CASCADE CONSTRAINTS;
DROP TABLE SCOTT.T_ENROLL CASCADE CONSTRAINTS;
DROP TABLE SCOTT.PROGRAMMING_LANGUAGE CASCADE CONSTRAINTS;
DROP TABLE SCOTT.QNA_FILE CASCADE CONSTRAINTS;
DROP TABLE SCOTT.QNA_MYREPLY CASCADE CONSTRAINTS;
DROP TABLE SCOTT.QNA_MYBOARD CASCADE CONSTRAINTS;
DROP TABLE SCOTT.STD_INFO CASCADE CONSTRAINTS;
DROP TABLE SCOTT.STUDY_LIKE CASCADE CONSTRAINTS;
DROP TABLE SCOTT.STUDY_TOOMUCHLIKE CASCADE CONSTRAINTS;
DROP TABLE SCOTT.S_PARTI_COMPLETE CASCADE CONSTRAINTS;
DROP TABLE SCOTT.TEACH_INFO CASCADE CONSTRAINTS;
DROP TABLE SCOTT.T_PARTI_COMPLETE CASCADE CONSTRAINTS;



/* Drop Sequences */

DROP SEQUENCE SCOTT.SEQ_QNA_FILE_NO;
DROP SEQUENCE SCOTT.SEQ_QNA_MYBOARD;
DROP SEQUENCE SCOTT.SEQ_QNA_MYREPLY;
DROP SEQUENCE SCOTT.S_ENROLL_SEQ;
DROP SEQUENCE SCOTT.S_PARTI_SEQ;
DROP SEQUENCE SCOTT.S_REPLY_SEQ;
DROP SEQUENCE SCOTT.T_ENROLL_SEQ;
DROP SEQUENCE SCOTT.T_PARTI_SEQ;
DROP SEQUENCE SCOTT.T_REPLY_SEQ;




/* Create Sequences */

CREATE SEQUENCE SCOTT.SEQ_QNA_FILE_NO INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 32 NOCACHE;
CREATE SEQUENCE SCOTT.SEQ_QNA_MYBOARD INCREMENT BY 1 MINVALUE 1 MAXVALUE 999999999999999999999 START WITH 61 CACHE 20;
CREATE SEQUENCE SCOTT.SEQ_QNA_MYREPLY INCREMENT BY 1 MINVALUE 1 MAXVALUE 99999999999999999999 START WITH 101 CACHE 20;
CREATE SEQUENCE SCOTT.S_ENROLL_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 541 CACHE 20;
CREATE SEQUENCE SCOTT.S_PARTI_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 161 CACHE 20;
CREATE SEQUENCE SCOTT.S_REPLY_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 81 CACHE 20;
CREATE SEQUENCE SCOTT.T_ENROLL_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 20060 CACHE 20;
CREATE SEQUENCE SCOTT.T_PARTI_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 121 CACHE 20;
CREATE SEQUENCE SCOTT.T_REPLY_SEQ INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 START WITH 103 CACHE 20;



/* Create Tables */

CREATE TABLE SCOTT.APPROVAL
(
	APP_ORGNAME varchar2(2000 char),
	APP_NEWNAME varchar2(2000 char),
	APP_ORGNAME2 varchar2(2000 char),
	APP_NEWNAME2 varchar2(2000 char),
	APP_GENDER varchar2(20 char),
	APP_PHONE1 varchar2(20 char),
	APP_PHONE2 varchar2(20 char),
	APP_PHONE3 varchar2(20 char),
	USER_EMAIL varchar2(100 char),
	APP_ADDR1 varchar2(50 char),
	APP_ADDR2 varchar2(100 char),
	APP_ADDR3 varchar2(50 char),
	APP_NUM number
);


CREATE TABLE SCOTT.PROGRAMMING_LANGUAGE
(
	LANGUAGE_NAME varchar2(200 char) NOT NULL,
	VIEWCNT number DEFAULT 0 
,
	LANGUAGE_IMAGE varchar2(200 char) NOT NULL,
	CONSTRAINT PROGRAMMING_LANGUAGE_PK PRIMARY KEY (LANGUAGE_NAME)
);


CREATE TABLE SCOTT.QNA_FILE
(
	FILE_NO number NOT NULL,
	QNA_BNO number NOT NULL,
	ORG_FILE_NAME varchar2(260 char) NOT NULL,
	STORED_FILE_NAME varchar2(36 char) NOT NULL,
	FILE_SIZE number,
	REGDATE date DEFAULT SYSDATE  NOT NULL,
	DEL_GB varchar2(1 char) DEFAULT '''N'' ' NOT NULL,
	CONSTRAINT SYS_C0011934 PRIMARY KEY (FILE_NO)
);


CREATE TABLE SCOTT.QNA_MYBOARD
(
	QNA_BNO number NOT NULL,
	QNA_TITLE varchar2(50 char),
	QNA_CONTENT varchar2(2000 char),
	QNA_WRITER varchar2(30 char) NOT NULL,
	QNA_REGDATE date DEFAULT sysdate 
,
	QNA_VIEWCNT number DEFAULT 0 
,
	CONSTRAINT QNABOARD_PK PRIMARY KEY (QNA_BNO)
);


CREATE TABLE SCOTT.QNA_MYREPLY
(
	QNA_BNO number NOT NULL,
	QNA_RNO number NOT NULL,
	QNA_CONTENT varchar2(1000 char),
	QNA_WRITER varchar2(30 char),
	QNA_REGDATE date DEFAULT sysdate 
,
	CONSTRAINT QNA_MYREPLY_PK PRIMARY KEY (QNA_BNO, QNA_RNO)
);


CREATE TABLE SCOTT.STD_INFO
(
	NO varchar2(10 char) DEFAULT '10',
	STD_ORGNAME varchar2(2000 char),
	STD_NEWNAME varchar2(2000 char),
	USER_ID varchar2(20 char) NOT NULL,
	USER_PWD varchar2(30 char),
	STD_GENDER varchar2(20 char),
	STD_PHONE1 varchar2(20 char),
	STD_PHONE2 varchar2(20 char),
	STD_PHONE3 varchar2(20 char),
	USER_EMAIL varchar2(20 char),
	STD_ADDR1 varchar2(50 char),
	STD_ADDR2 varchar2(100 char),
	STD_ADDR3 varchar2(50 char),
	CONSTRAINT SYS_C0011925 PRIMARY KEY (USER_ID)
);


CREATE TABLE SCOTT.STUDY_LIKE
(
	S_NO number NOT NULL,
	S_USERID varchar2(200 char) NOT NULL
);


CREATE TABLE SCOTT.STUDY_TOOMUCHLIKE
(
	S_NO number NOT NULL,
	S_USERID varchar2(100 char) NOT NULL
);


CREATE TABLE SCOTT.S_ENROLL
(
	S_NO number NOT NULL,
	S_USERID varchar2(20 char) NOT NULL,
	S_CATEGORY varchar2(200 char) NOT NULL,
	S_TITLE varchar2(100 char) NOT NULL,
	S_STARTDATE date NOT NULL,
	S_ENDDATE date,
	S_DAY varchar2(30 char),
	S_POSTNUM number,
	S_PLACE varchar2(100 char),
	S_CONTENT varchar2(3000 char),
	S_PHOTO varchar2(50 char),
	S_LEVEL varchar2(10 char) NOT NULL,
	S_PEOPLE number DEFAULT 0  NOT NULL,
	S_CREADATE date DEFAULT sysdate 
,
	S_UPDATEDATE date,
	S_INTRO varchar2(3000 char),
	S_VIEWCNT number DEFAULT 0 ,
	S_PARTI number DEFAULT 0 ,
	S_BNO_LIKECNT number DEFAULT 0 ,
	STD_ORGNAME varchar2(300 char) DEFAULT '''http://i66.tinypic.com/ng7ue1.jpg'' ',
	STARSCORE number DEFAULT 0,
	STARSCORE_PARTI number DEFAULT 0,
	CONSTRAINT S_ENROLL_PK PRIMARY KEY (S_NO)
);


CREATE TABLE SCOTT.S_PARTI
(
	P_NO number NOT NULL,
	S_NO number,
	P_USERID varchar2(30 char),
	P_INTRO varchar2(100 char),
	P_TELL number(30),
	P_REGDATE date DEFAULT sysdate ,
	STARSCORE_PARTI number DEFAULT 0,
	CONSTRAINT S_PARTI_PK PRIMARY KEY (P_NO)
);


CREATE TABLE SCOTT.S_PARTI_COMPLETE
(
	P_NO number NOT NULL,
	S_NO number,
	P_USERID varchar2(30 char),
	P_INTRO varchar2(100 char),
	P_TELL number(30),
	P_REGDATE date,
	STARSCORE_PARTI number,
	CONSTRAINT S_PARTI_COMPLETE_PK PRIMARY KEY (P_NO)
);


CREATE TABLE SCOTT.S_REPLY
(
	R_NO number NOT NULL,
	S_NO number,
	R_USERID varchar2(30 char),
	R_CONTENT varchar2(3000 char),
	R_REGDATE date DEFAULT sysdate 
,
	CONSTRAINT S_REPLY_PK PRIMARY KEY (R_NO)
);


CREATE TABLE SCOTT.TEACH_INFO
(
	NO varchar2(10 char) DEFAULT '20',
	TEACH_ORGNAME varchar2(2000 char),
	TEACH_NEWNAME varchar2(2000 char),
	TEACH_ORGNAME2 varchar2(2000 char),
	TEACH_NEWNAME2 varchar2(2000 char),
	USER_ID varchar2(20 char),
	USER_PWD varchar2(30 char),
	TEACH_GENDER varchar2(20 char),
	TEACH_PHONE1 varchar2(20 char),
	TEACH_PHONE2 varchar2(20 char),
	TEACH_PHONE3 varchar2(20 char),
	USER_EMAIL varchar2(100 char),
	TEACH_ADDR1 varchar2(50 char),
	TEACH_ADDR2 varchar2(200 char),
	TEACH_ADDR3 varchar2(50 char)
);


CREATE TABLE SCOTT.T_ENROLL
(
	T_NO number NOT NULL,
	T_USERID varchar2(30 char) NOT NULL,
	T_CATEGORY varchar2(200 char) NOT NULL,
	T_TITLE varchar2(100 char) NOT NULL,
	T_STARTDATE date NOT NULL,
	T_ENDDATE date,
	T_DAY varchar2(30 char) NOT NULL,
	T_POSTNUM number,
	T_PLACE varchar2(100 char) NOT NULL,
	T_CONTENT varchar2(3000 char) NOT NULL,
	T_PHOTO varchar2(50 char),
	T_LEVEL varchar2(10 char) NOT NULL,
	T_PEOPLE number DEFAULT 0  NOT NULL,
	T_PARTI number DEFAULT 0 ,
	T_CREADATE date DEFAULT sysdate,
	T_UPDATEDATE date,
	T_URL varchar2(500 char),
	T_LICENSE varchar2(50 char),
	T_VIEWCNT number DEFAULT 0 ,
	T_INTRO varchar2(3000 char),
	T_PRICE varchar2(50 char) NOT NULL,
	STARSCORE number DEFAULT 0,
	STARSCORE_PARTI number DEFAULT 0,
	TEACH_ORGNAME varchar2(200 char) DEFAULT '''http://i66.tinypic.com/ng7ue1.jpg'' ',
	CONSTRAINT SYS_C0011230 PRIMARY KEY (T_NO)
);


CREATE TABLE SCOTT.T_PARTI
(
	P_NO number NOT NULL,
	T_NO number NOT NULL,
	P_USERID varchar2(30 char) NOT NULL,
	P_INTRO varchar2(50 char),
	P_TELL number(11),
	P_REGDATE date DEFAULT sysdate 
,
	STARSCORE_PARTI number DEFAULT 0,
	CONSTRAINT T_PARTI_PK PRIMARY KEY (P_NO)
);


CREATE TABLE SCOTT.T_PARTI_COMPLETE
(
	P_NO number NOT NULL,
	T_NO number NOT NULL,
	P_USERID varchar2(30 char) NOT NULL,
	P_INTRO varchar2(50 char),
	P_TELL number(11),
	P_REGDATE date,
	STARSCORE_PARTI number
);


CREATE TABLE SCOTT.T_REPLY
(
	R_NO number NOT NULL,
	T_NO number,
	R_USERID varchar2(30 char),
	R_CONTENT varchar2(3000 char),
	R_REGDATE date DEFAULT sysdate 
,
	CONSTRAINT T_REPLY_PK PRIMARY KEY (R_NO)
);



/* Create Foreign Keys */

ALTER TABLE SCOTT.S_ENROLL
	ADD CONSTRAINT S_ENROLL_PROGRAMMING_NAME_FK FOREIGN KEY (S_CATEGORY)
	REFERENCES SCOTT.PROGRAMMING_LANGUAGE (LANGUAGE_NAME)
;


ALTER TABLE SCOTT.T_ENROLL
	ADD CONSTRAINT T_ENROLL_PROGRAMMING_NAME_FK FOREIGN KEY (T_CATEGORY)
	REFERENCES SCOTT.PROGRAMMING_LANGUAGE (LANGUAGE_NAME)
;


ALTER TABLE SCOTT.QNA_FILE
	ADD CONSTRAINT QNA_FILE_QNA_BOARD_FK FOREIGN KEY (QNA_BNO)
	REFERENCES SCOTT.QNA_MYBOARD (QNA_BNO)
;


ALTER TABLE SCOTT.QNA_MYREPLY
	ADD CONSTRAINT QNA_MYREPLY_QNA_BOARD_FK FOREIGN KEY (QNA_BNO)
	REFERENCES SCOTT.QNA_MYBOARD (QNA_BNO)
;


ALTER TABLE SCOTT.S_ENROLL
	ADD CONSTRAINT S_ENROLL_STD_INFO_FK FOREIGN KEY (S_USERID)
	REFERENCES SCOTT.STD_INFO (USER_ID)
;


ALTER TABLE SCOTT.S_PARTI
	ADD CONSTRAINT FK_S_NO_S_PARTI_ENROLL FOREIGN KEY (S_NO)
	REFERENCES SCOTT.S_ENROLL (S_NO)
	ON DELETE CASCADE
;


ALTER TABLE SCOTT.S_REPLY
	ADD CONSTRAINT FK_S_NO_S_ENROLL FOREIGN KEY (S_NO)
	REFERENCES SCOTT.S_ENROLL (S_NO)
	ON DELETE CASCADE
;


ALTER TABLE SCOTT.T_PARTI
	ADD CONSTRAINT FK_T_NO_T_PARTI_ENROLL FOREIGN KEY (T_NO)
	REFERENCES SCOTT.T_ENROLL (T_NO)
	ON DELETE CASCADE
;


ALTER TABLE SCOTT.T_REPLY
	ADD CONSTRAINT FK_T_NO_T_ENROLL FOREIGN KEY (T_NO)
	REFERENCES SCOTT.T_ENROLL (T_NO)
	ON DELETE CASCADE
;



